# 端口
server:
  port: 8900
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/graduationdesign?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zwtwoshichaoren
  # 配置thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
  # 配置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
# 日志级别
logging:
  level:
    org.yf: debug
    root: info
# mybatis-plus配置
mybatis-plus:
  configuration:
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml