# 端口
server:
  port: 8900
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://118.24.197.243:3306/graduationdesign
    username: root
    password: mysql!@#$1234
  # 配置thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
# 日志级别
logging:
  level:
    org.yf: debug
    root: info
# mybatis-plus配置
mybatis-plus:
  configuration:
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml