# 端口
server:
  port: 9000
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/graduationdesign?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zwtwoshichaoren
  # 配置thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
# 日志级别
logging:
  level:
    org.yf: debug
    root: info
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl